spring.datasource.jndi-name=java:/personalfinancesDS
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.open-in-view=true

# Add timezone to the logs
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss

server.servlet.context-path=/personalfinances

spring.mvc.format.date=dd/MM/yyyy
spring.mvc.format.date-time=dd/MM/yyyy HH:mm:ss
spring.mvc.format.time=HH:mm:ss

spring.jackson.serialization.write-dates-as-timestamps=false

app.version=@project.version@
